import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Building2, Globe2, Mail, MapPin, MessageCircle, Navigation, Phone } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ContactForm } from "@/components/contact-form";
import { SectionLabel } from "@/components/ui";
import { enquiryServices } from "@/lib/content";
import { getContactDetails } from "@/lib/contact";

export const metadata: Metadata = { title: "Contacts — Let’s connect", description: "Contact ZAPAL SK in Bratislava. Tell us about your materials, supply chain, or logistics requirements through our email and WhatsApp enquiry form." };
export const dynamic = "force-dynamic";

export default async function ContactsPage({ searchParams }: { searchParams: Promise<{ service?: string; channel?: string }> }) {
  const query = await searchParams;
  const contact = getContactDetails();
  const initialService = query.service && enquiryServices.includes(query.service) ? query.service : "General enquiry";
  const initialChannel = query.channel === "whatsapp" ? "whatsapp" : "email";
  return <main id="main-content"><PageHero title={"Good business starts\nwith a conversation."} description="A question, a project, a new possibility. Whatever brings you here, we’re glad to connect." eyebrow="LET’S TALK" breadcrumb="Contacts" image="/images/bratislava.jpg" imageAlt="The Bratislava skyline and the Danube River near the ZAPAL SK registered address" compact />
    <section className="section contact-section"><div className="container contact-grid"><div className="contact-info"><SectionLabel>YOUR NEXT CONNECTION</SectionLabel><h2>Let’s find your<br />way forward.</h2><p className="contact-intro">Tell us what’s on your mind. We’ll connect your needs with the right expertise.</p><div className="contact-details"><div className="contact-detail"><span className="contact-icon"><MapPin size={21} strokeWidth={1.5} /></span><div><span className="detail-label">FIND US</span><h3>{contact.company}</h3><a href={contact.directionsUrl} target="_blank" rel="noopener noreferrer">{contact.address}<ArrowUpRight size={14} /></a></div></div><div className="contact-detail"><span className="contact-icon"><Mail size={20} strokeWidth={1.5} /></span><div><span className="detail-label">EMAIL ENQUIRIES</span>{contact.email ? <a href={`mailto:${contact.email}`} className="contact-direct">{contact.email}<ArrowUpRight size={15} /></a> : <><a href="#enquiry-form" className="contact-direct">Send us an enquiry<ArrowUpRight size={15} /></a><p>Start with the form. We’ll take it from there.</p></>}</div></div><div className="contact-detail"><span className="contact-icon"><MessageCircle size={21} strokeWidth={1.5} /></span><div><span className="detail-label">PREFER WHATSAPP?</span><Link className="contact-direct" href="/contacts?channel=whatsapp#enquiry-form">Let’s start a conversation<ArrowUpRight size={15} /></Link><p>A prepared message, ready when you are.</p></div></div>{contact.phone && <div className="contact-detail"><span className="contact-icon"><Phone size={20} strokeWidth={1.5} /></span><div><span className="detail-label">GIVE US A CALL</span><a href={`tel:${contact.phone.replace(/[^\d+]/g, "")}`} className="contact-direct">{contact.phone}<ArrowUpRight size={15} /></a></div></div>}</div><div className="company-registration"><Building2 size={18} strokeWidth={1.4} /><p><strong>Registered in Slovakia</strong><span>IČO: {contact.registration}</span><span>IČ DPH: {contact.vat}</span></p></div><div className="contact-personal"><Globe2 size={29} strokeWidth={1.2} /><p>Local roots.<br /><strong>A world of possibilities.</strong></p></div></div><ContactForm key={`${initialChannel}-${initialService}`} initialService={initialService} initialChannel={initialChannel} emailConfigured={Boolean(contact.email)} emailDeliveryEnabled={contact.emailDeliveryEnabled} whatsappConfigured={Boolean(contact.whatsapp)} /></div></section>
    <section className="map-section"><div className="container"><div className="map-heading"><div><SectionLabel>AT THE HEART OF EUROPE</SectionLabel><h2>Find us in Bratislava.</h2></div><a href={contact.directionsUrl} target="_blank" rel="noopener noreferrer" className="text-link">Get directions<Navigation size={16} /></a></div><div className="map-container"><iframe src={contact.mapUrl} title={`Interactive map: ${contact.company}, ${contact.address}`} width="1200" height="410" loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade" /><div className="map-address"><span className="map-pin"><MapPin size={21} /></span><div><strong>ZAPAL SK</strong><span>{contact.address}</span></div><a href={contact.directionsUrl} target="_blank" rel="noopener noreferrer" aria-label="Open directions in Google Maps"><ArrowUpRight size={21} /></a></div></div><p className="map-footnote">Map provided by Google Maps. <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google privacy policy<ArrowUpRight size={10} /></a></p></div></section></main>;
}
