"use client";

import Link from "next/link";
import { ArrowUpRight, Building2, Globe2, Mail, MapPin, MessageCircle, Navigation, Phone } from "lucide-react";
import { PageHero } from "./page-hero";
import { ContactForm } from "./contact-form";
import { SectionLabel } from "./ui";
import { useLanguage } from "./language-provider";

type ContactProps = {
  company: string; address: string; email: string; phone: string; whatsapp: string;
  registration: string; vat: string; directionsUrl: string; mapUrl: string; emailDeliveryEnabled: boolean;
  initialService: string; initialChannel: "email" | "whatsapp"; initialServiceIndex: number;
};

export function ContactsView(props: ContactProps) {
  const { t } = useLanguage();
  const c = t.contacts;
  return <main id="main-content"><PageHero title={c.title} description={c.description} eyebrow={c.eyebrow} breadcrumb={c.breadcrumb} image="/images/bratislava.jpg" imageAlt="The Bratislava skyline and the Danube River near the ZAPAL SK registered address" compact />
    <section className="section contact-section"><div className="container contact-grid"><div className="contact-info"><SectionLabel>{c.infoEyebrow}</SectionLabel><h2 className="preserve-lines">{c.infoTitle}</h2><p className="contact-intro">{c.infoIntro}</p><div className="contact-details"><div className="contact-detail"><span className="contact-icon"><MapPin size={21} strokeWidth={1.5} /></span><div><span className="detail-label">{c.findUs}</span><h3>{props.company}</h3><a href={props.directionsUrl} target="_blank" rel="noopener noreferrer">{props.address}<ArrowUpRight size={14} /></a></div></div><div className="contact-detail"><span className="contact-icon"><Mail size={20} strokeWidth={1.5} /></span><div><span className="detail-label">{c.emailEnquiries}</span>{props.email ? <a href={`mailto:${props.email}`} className="contact-direct">{props.email}<ArrowUpRight size={15} /></a> : <><a href="#enquiry-form" className="contact-direct">{c.sendEnquiry}<ArrowUpRight size={15} /></a><p>{c.emailStart}</p></>}</div></div><div className="contact-detail"><span className="contact-icon"><MessageCircle size={21} strokeWidth={1.5} /></span><div><span className="detail-label">{c.preferWhatsapp}</span><Link className="contact-direct" href="/contacts?channel=whatsapp#enquiry-form">{c.whatsappStart}<ArrowUpRight size={15} /></Link><p>{c.whatsappNote}</p></div></div>{props.phone && <div className="contact-detail"><span className="contact-icon"><Phone size={20} strokeWidth={1.5} /></span><div><span className="detail-label">{c.callUs}</span><a href={`tel:${props.phone.replace(/[^\d+]/g, "")}`} className="contact-direct">{props.phone}<ArrowUpRight size={15} /></a></div></div>}</div><div className="company-registration"><Building2 size={18} strokeWidth={1.4} /><p><strong>{c.registered}</strong><span>IČO: {props.registration}</span><span>IČ DPH: {props.vat}</span></p></div><div className="contact-personal"><Globe2 size={29} strokeWidth={1.2} /><p>{c.personal}<br /><strong>{c.personalStrong}</strong></p></div></div><ContactForm key={`${props.initialChannel}-${props.initialServiceIndex}`} initialServiceIndex={props.initialServiceIndex} initialChannel={props.initialChannel} emailConfigured={Boolean(props.email)} emailDeliveryEnabled={props.emailDeliveryEnabled} whatsappConfigured={Boolean(props.whatsapp)} /></div></section>
    <section className="map-section"><div className="container"><div className="map-heading"><div><SectionLabel>{c.mapEyebrow}</SectionLabel><h2>{c.mapTitle}</h2></div><a href={props.directionsUrl} target="_blank" rel="noopener noreferrer" className="text-link">{t.common.getDirections}<Navigation size={16} /></a></div><div className="map-container"><iframe src={props.mapUrl} title={`${c.mapTitle} ${props.company}, ${props.address}`} width="1200" height="410" loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade" /><div className="map-address"><span className="map-pin"><MapPin size={21} /></span><div><strong>ZAPAL SK</strong><span>{props.address}</span></div><a href={props.directionsUrl} target="_blank" rel="noopener noreferrer" aria-label={t.common.getDirections}><ArrowUpRight size={21} /></a></div></div><p className="map-footnote">{c.mapFootnote} <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">{c.googlePrivacy}<ArrowUpRight size={10} /></a></p></div></section></main>;
}
